service: PUF-Slack
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.10
  timeout: 30 # maximum of 30 second for api gateway
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline